[project]
name = "macha"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyyaml>=6.0.2",
    "colorlog>=6.8.2",
    "sqlalchemy>=2.0.0",
    "aiosqlite>=0.20.0",
    "psutil>=6.1.0",
    "pydantic>=2.0.0",
    "picamera2>=0.3.27",
    "ruff>=0.11.13",
]
[tool.uv.pip]
break-system-packages = true
