name: PR Tests & Lint

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      
      - name: Set up Python
        run: uv python install
      
      - name: Install dependencies
        run: uv sync --all-extras
      
      - name: Run ruff linter
        run: uv run ruff check .
      
      - name: Run ruff formatter
        run: uv run ruff format --check .
      
      - name: Run tests
        run: uv run pytest tests/ -v --tb=short
        
      - name: Check Python syntax
        run: uv run python -m py_compile src/*.py